### ISSUE TITLE
Rainbow Kit 0.12.8

### ISSUE THREAD

**Issue by kkatusic** [GeneralMagicio/next-web3-starter#3]
Can you try this setup with new Rainbow Kit package version 0.12.8? thx

**Comment by marthendalnunes** [comment]
@kkatusic good point, I'll update it to Rainbowkit v1

**Comment by kkatusic** [comment]
Excellent than I will try again, just for testing connection on various devices, we need that for Praise ;)

**Comment by marthendalnunes** [comment]
@kkatusic upgraded to V1

**Comment by kkatusic** [comment]
> @kkatusic upgraded to V1

thx
